#%%
# Build candidate mappings from 9th sector/fuel pairs to ESTO flow/product pairs
# using code prefix matching against the full ESTO dataset.
# NOTE: We observed no projected-year (> base year) subtotal pattern differences
# across economies, so mapping focuses on > base year data.
#final m,oved to config\ninth_pairs_to_esto_pairs.csv
#%%

r"""

This mapping connects 9th sector/fuel pairs to ESTO flow/product pairs.
It is built from the most detailed non‑x 9th sector and fuel labels and includes some one‑to‑many and many‑to‑one relationships (but no many‑to‑many).
Main generator: codebase/scrapbook/esto_and_9th_labels_to_names_code/build_ninth_pair_to_esto_pair_candidates.py
9th flattening / projected‑nonzero pairs: codebase/scrapbook/esto_and_9th_labels_to_names_code/build_ninth_flattened_pairs.py
Independent flow/product mappings input: config/independent product flow mappings.xlsx

ninth_pair_exists tells you whether a real 9th sector/fuel pair exists for that row.
If ninth_pair_exists is False or blank, there is no 9th sector/fuel pair mapped to the existing ESTO flow/product pair.
These are likely very minor datapoints across APERC, but if you do need to map them then you can use what is in orig_9th_sector and orig_9th_fuel and copy/paste those values.

Do not overwrite C:\Users\Work\github\leap_utilities\config\ninth_pairs_to_esto_pairs_MASTER.csv since that contains a copy of the mappings, and some of them had to be done manually.
Most of the file was generated by code, but the master file includes manual fixes.

The mapping was generated in stages:

1. direct pair matching (build_ninth_pair_to_esto_pair_candidates.py)
2. independent flow/product mappings (config/independent product flow mappings.xlsx)
3. hierarchy backoff for strict projected‑nonzero output (build_ninth_pair_to_esto_pair_candidates.py, using 9th data hierarchy)

Because one‑to‑many mappings exist, converting from 9th to ESTO or ESTO to 9th requires splitting values.
Use the proportional allocation approach in codebase/ninth_projection_mapping.py (based on base‑year shares from the other dataset).

There is also a strict projected‑nonzero version that removes 9th pairs with zero values across projection years.
Use that if you only want pairs with non‑zero 9th projections, but note it can remove some ESTO‑only pairs.

"""



from __future__ import annotations

from pathlib import Path
import importlib.util
import re
import os

import pandas as pd
from codebase.utilities.master_config import config_table_exists, read_config_table
REPO_ROOT = Path(__file__).resolve().parents[3]
NINTH_PAIR_PATH = REPO_ROOT / "outputs" / "ninth_pairs_base_year_nonzero.csv"
NINTH_FLATTENED_PATH = REPO_ROOT / "outputs" / "ninth_flattened_rows.csv"
ESTO_DATA_PATH = REPO_ROOT / "data" / "00APEC_2024_low.csv"
ESTO_SUBTOTAL_MAPPING = REPO_ROOT / "config" / "ESTO_subtotal_mapping.xlsx"
INDEPENDENT_MAPPING_PATH = REPO_ROOT / "config" / "independent product flow mappings.xlsx"
NINTH_REFERENCE_PATH = REPO_ROOT / "config" / "sector_fuel_codes_to_names.xlsx"
OUTPUT_PATH = REPO_ROOT / "outputs" / "ninth_pairs_to_esto_candidates.csv"
OUTPUT_STRICT_PATH = REPO_ROOT / "outputs" / "ninth_pairs_to_esto_candidates_projected_nonzero.csv"
UNMATCHED_PATH = REPO_ROOT / "outputs" / "ninth_pairs_to_esto_unmatched.csv"
ESTO_LABELS_PATH = REPO_ROOT / "outputs" / "esto_flows_products_list.csv"

NINTH_CODE_PATTERN = re.compile(r"^\d+(?:_\d+)*")
ESTO_CODE_PATTERN = re.compile(r"^\d+(?:\.\d+)*")
SKIP_LABEL_TOKENS = ("_unallocated", "_x")
NONSPECIFIED_TOKENS = ("nonspecified", "non-specified")
BASE_YEAR = 2022
PROJECTED_START_YEAR = 2023

UTILS_PATH = REPO_ROOT / "codebase" / "scrapbook" / "utilities.py"
spec = importlib.util.spec_from_file_location("utilities", UTILS_PATH)
utilities = importlib.util.module_from_spec(spec)
if spec and spec.loader:
    spec.loader.exec_module(utilities)
else:
    raise ImportError(f"Failed to load utilities module from {UTILS_PATH}")

apply_matt_subtotal_mapping = utilities.apply_matt_subtotal_mapping
filter_matt_subtotals = utilities.filter_matt_subtotals


def _extract_ninth_code(label: str) -> str:
    match = NINTH_CODE_PATTERN.match(label or "")
    return match.group(0) if match else ""


def _extract_esto_code(label: str) -> str:
    match = ESTO_CODE_PATTERN.match(label or "")
    return match.group(0) if match else ""


def _build_code_match_method(levels_up: int) -> str:
    levels_up = max(int(levels_up), 0)
    if levels_up == 0:
        return "direct_code_match"
    return f"parent_code_match_{levels_up}_levels_up"


def _build_code_index(labels: list[str]) -> dict[str, list[str]]:
    index: dict[str, list[str]] = {}
    for label in labels:
        code = _extract_esto_code(label)
        if not code:
            continue
        index.setdefault(code, []).append(label)
    return index


def _match_code_to_label(
    ninth_label: str,
    index: dict[str, list[str]],
    nonspecified_by_top: dict[str, str],
) -> tuple[str, str]:
    lowered = (ninth_label or "").lower()
    if any(token in lowered for token in SKIP_LABEL_TOKENS):
        return "", "skipped_x_or_unallocated"
    code = _extract_ninth_code(ninth_label)
    if not code:
        return "", ""
    dotted = code.replace("_", ".")
    parts = dotted.split(".")
    for i in range(len(parts), 0, -1):
        candidate = ".".join(parts[:i])
        if candidate in index:
            method = _build_code_match_method(len(parts) - i)
            return index[candidate][0], method
    return "", ""

def _is_x_like(label: str) -> bool:
    lowered = (label or "").lower()
    return any(token in lowered for token in SKIP_LABEL_TOKENS)

def _build_independent_map(
    df: pd.DataFrame,
    ninth_keys: list[str],
    esto_keys: list[str],
) -> dict[str, list[str]]:
    ninth_col = next((col for col in ninth_keys if col in df.columns), None)
    esto_col = next((col for col in esto_keys if col in df.columns), None)
    if not ninth_col or not esto_col:
        return {}
    mapping = (
        df[[ninth_col, esto_col]]
        .dropna()
        .assign(
            ninth=lambda d: d[ninth_col].astype(str).str.strip(),
            esto=lambda d: d[esto_col].astype(str).str.strip(),
        )
    )
    mapping = mapping[mapping["ninth"] != ""]
    mapping = mapping.drop_duplicates()
    return (
        mapping.groupby("ninth")["esto"]
        .apply(lambda series: sorted({val for val in series if val}))
        .to_dict()
    )

def _build_parent_map_from_data(ninth_df: pd.DataFrame, columns: list[str]) -> dict[str, list[str]]:
    parent_map: dict[str, set[str]] = {}
    for _, row in ninth_df.iterrows():
        values = [str(row.get(col) or "").strip() for col in columns]
        for idx, label in enumerate(values):
            if not label or label.lower() == "x":
                continue
            parent = ""
            for parent_idx in range(idx - 1, -1, -1):
                candidate = values[parent_idx]
                if candidate and candidate.lower() != "x":
                    parent = candidate
                    break
            if parent:
                parent_map.setdefault(label, set()).add(parent)
    return {key: sorted(values) for key, values in parent_map.items()}

def _build_level_chain(label: str, parent_map: dict[str, list[str]]) -> list[list[str]]:
    if not label:
        return []
    levels: list[list[str]] = [[label]]
    seen = {label}
    while True:
        current = levels[-1]
        next_level: list[str] = []
        for item in current:
            for parent in parent_map.get(item, []):
                if parent not in seen:
                    next_level.append(parent)
                    seen.add(parent)
        if not next_level:
            break
        levels.append(sorted(next_level))
    return levels


def main() -> None:
    if not NINTH_PAIR_PATH.exists():
        raise FileNotFoundError(f"Missing pair list: {NINTH_PAIR_PATH}")

    ninth_pairs = pd.read_csv(NINTH_PAIR_PATH, dtype=str).fillna("")
    ninth_pairs_set = set(
        zip(ninth_pairs["sector"].fillna(""), ninth_pairs["fuel"].fillna(""))
        if {"sector", "fuel"}.issubset(ninth_pairs.columns)
        else zip(ninth_pairs["9th_sector"].fillna(""), ninth_pairs["9th_fuel"].fillna(""))
    )
    esto_columns = pd.read_csv(ESTO_DATA_PATH, nrows=0).columns.tolist()
    year_cols = [col for col in esto_columns if str(col).isdigit()]
    esto_usecols = ["flows", "products"] + year_cols
    esto_raw = pd.read_csv(ESTO_DATA_PATH, usecols=esto_usecols, dtype=str).fillna("")
    esto_labeled = apply_matt_subtotal_mapping(esto_raw, ESTO_SUBTOTAL_MAPPING)
    esto_clean = filter_matt_subtotals(esto_labeled)

    flow_labels = sorted({label.strip() for label in esto_clean["flows"] if label.strip()})
    product_labels = sorted({label.strip() for label in esto_clean["products"] if label.strip()})

    def _build_nonspecified_map(labels: list[str]) -> dict[str, str]:
        mapping = {}
        for label in labels:
            lowered = label.lower()
            if not any(token in lowered for token in NONSPECIFIED_TOKENS):
                continue
            code = _extract_esto_code(label)
            if not code:
                continue
            top = code.split(".")[0]
            mapping.setdefault(top, label)
        return mapping

    nonspecified_flows = _build_nonspecified_map(flow_labels)
    nonspecified_products = _build_nonspecified_map(product_labels)

    flow_index = _build_code_index(flow_labels)
    product_index = _build_code_index(product_labels)

    product_map = {}
    flow_map = {}
    if config_table_exists(INDEPENDENT_MAPPING_PATH, sheet_name="product"):
        prod_df = read_config_table(INDEPENDENT_MAPPING_PATH, sheet_name="product", dtype=str).fillna("")
        flow_df = read_config_table(INDEPENDENT_MAPPING_PATH, sheet_name="flow", dtype=str).fillna("")
        product_map = _build_independent_map(
            prod_df,
            ["9th_fuel", "9th_label", "9th_product"],
            ["esto_product", "esto_label", "esto_product_label"],
        )
        flow_map = _build_independent_map(
            flow_df,
            ["9th_sector", "9th_label", "9th_flow"],
            ["esto_flow", "esto_label", "esto_flow_label"],
        )
    # Build reverse lookup for ESTO -> 9th fallback when only ESTO pairs exist.
    product_reverse_map = {}
    for ninth_label, esto_labels in product_map.items():
        for label in esto_labels:
            product_reverse_map.setdefault(label, []).append(ninth_label)
    flow_reverse_map = {}
    for ninth_label, esto_labels in flow_map.items():
        for label in esto_labels:
            flow_reverse_map.setdefault(label, []).append(ninth_label)

    rows = []
    unmatched = []
    for _, row in ninth_pairs.iterrows():
        sector = row.get("sector", "")
        fuel = row.get("fuel", "")
        flow_label, flow_method = _match_code_to_label(
            sector, flow_index, nonspecified_flows
        )
        product_label, product_method = _match_code_to_label(
            fuel, product_index, nonspecified_products
        )

        if flow_label and product_label:
            rows.append(
                {
                    "9th_sector": sector,
                    "9th_fuel": fuel,
                    "esto_flow": flow_label,
                    "esto_product": product_label,
                    "sector_match_method": flow_method,
                    "fuel_match_method": product_method,
                }
            )
        else:
            unmatched.append(
                {
                    "9th_sector": sector,
                    "9th_fuel": fuel,
                    "sector_match_method": flow_method,
                    "fuel_match_method": product_method,
                }
            )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    candidates_df = pd.DataFrame(rows)
    unmatched_df = pd.DataFrame(unmatched)

    # Basic validation checks for common issues (dupes, missing keys).
    if not candidates_df.empty:
        dup_pair_rows = candidates_df.duplicated(
            subset=["9th_sector", "9th_fuel", "esto_flow", "esto_product"], keep=False
        )
        if dup_pair_rows.any():
            print(
                f"[WARN] Duplicate pair rows detected: {dup_pair_rows.sum()} "
                "(consider deduping or reviewing source mappings)."
            )
        missing_esto = candidates_df[
            (candidates_df["esto_flow"].fillna("") == "")
            | (candidates_df["esto_product"].fillna("") == "")
        ]
        if not missing_esto.empty:
            print(
                f"[WARN] Candidate rows missing esto_flow/product: {len(missing_esto)}"
            )
        missing_9th = candidates_df[
            (candidates_df["9th_sector"].fillna("") == "")
            | (candidates_df["9th_fuel"].fillna("") == "")
        ]
        if not missing_9th.empty:
            print(
                f"[WARN] Candidate rows missing 9th_sector/9th_fuel: {len(missing_9th)}"
            )

    mapped_flows = set(candidates_df["esto_flow"].dropna()) if not candidates_df.empty else set()
    mapped_products = set(candidates_df["esto_product"].dropna()) if not candidates_df.empty else set()
    mapped_pairs = set(
        zip(
            candidates_df["esto_flow"].fillna(""),
            candidates_df["esto_product"].fillna(""),
        )
    ) if not candidates_df.empty else set()

    # Fallback: exact independent mapping for missing pairs.
    if not unmatched_df.empty and (product_map or flow_map):
        fallback_rows = []
        remaining = []
        for _, row in unmatched_df.iterrows():
            sector = row.get("9th_sector", "")
            fuel = row.get("9th_fuel", "")
            is_x = _is_x_like(sector) or _is_x_like(fuel)
            flows = flow_map.get(sector, [])
            products = product_map.get(fuel, [])
            if flows and products:
                for flow in flows:
                    for product in products:
                        if (flow, product) in mapped_pairs:
                            continue
                        fallback_rows.append(
                            {
                                "9th_sector": sector,
                                "9th_fuel": fuel,
                                "esto_flow": flow,
                                "esto_product": product,
                                "sector_match_method": (
                                    "independent_table_direct_match_x_category"
                                    if is_x
                                    else "independent_table_direct_match"
                                ),
                                "fuel_match_method": (
                                    "independent_table_direct_match_x_category"
                                    if is_x
                                    else "independent_table_direct_match"
                                ),
                            }
                        )
                        mapped_pairs.add((flow, product))
            else:
                remaining.append(row.to_dict())
        if fallback_rows:
            candidates_df = pd.concat([candidates_df, pd.DataFrame(fallback_rows)], ignore_index=True)
        unmatched_df = pd.DataFrame(remaining)

    # Final fallback: map _x/_unallocated labels to nonspecified ESTO categories.
    if not unmatched_df.empty:
        fallback_rows = []
        remaining = []
        for _, row in unmatched_df.iterrows():
            sector = row.get("9th_sector", "")
            fuel = row.get("9th_fuel", "")
            if not (_is_x_like(sector) or _is_x_like(fuel)):
                remaining.append(row.to_dict())
                continue
            flow = ""
            product = ""
            if _is_x_like(sector):
                top = _extract_ninth_code(sector).split("_")[0] if _extract_ninth_code(sector) else ""
                flow = nonspecified_flows.get(top, "")
            if _is_x_like(fuel):
                top = _extract_ninth_code(fuel).split("_")[0] if _extract_ninth_code(fuel) else ""
                product = nonspecified_products.get(top, "")
            if flow and product and (flow, product) not in mapped_pairs:
                fallback_rows.append(
                    {
                        "9th_sector": sector,
                        "9th_fuel": fuel,
                        "esto_flow": flow,
                        "esto_product": product,
                        "sector_match_method": "nonspecified_category_fallback",
                        "fuel_match_method": "nonspecified_category_fallback",
                    }
                )
                mapped_pairs.add((flow, product))
            else:
                remaining.append(row.to_dict())
        if fallback_rows:
            candidates_df = pd.concat([candidates_df, pd.DataFrame(fallback_rows)], ignore_index=True)
        unmatched_df = pd.DataFrame(remaining)

    esto_nonzero = esto_clean.copy()
    base_year_col = str(BASE_YEAR)
    if base_year_col not in esto_nonzero.columns:
        raise ValueError(f"Missing base year column {base_year_col} in ESTO data.")
    numeric = pd.to_numeric(esto_nonzero[base_year_col], errors="coerce").fillna(0)
    nonzero_mask = numeric.abs() != 0
    esto_nonzero = esto_nonzero[nonzero_mask]
    nonzero_pairs = set(
        zip(esto_nonzero["flows"].fillna(""), esto_nonzero["products"].fillna(""))
    )

    extra_rows = []
    for flow, product in sorted(nonzero_pairs):
        if (flow, product) in mapped_pairs:
            continue
        ninth_sectors = sorted({val for val in flow_reverse_map.get(flow, []) if val})
        ninth_fuels = sorted({val for val in product_reverse_map.get(product, []) if val})
        if ninth_sectors and ninth_fuels:
            for ninth_sector in ninth_sectors:
                for ninth_fuel in ninth_fuels:
                    extra_rows.append(
                        {
                            "9th_sector": ninth_sector,
                            "9th_fuel": ninth_fuel,
                            "esto_flow": flow,
                            "esto_product": product,
                            "sector_match_method": "independent_table_reverse_lookup",
                            "fuel_match_method": "independent_table_reverse_lookup",
                        }
                    )
        else:
            extra_rows.append(
                {
                    "9th_sector": "",
                    "9th_fuel": "",
                    "esto_flow": flow,
                    "esto_product": product,
                    "sector_match_method": "unmapped_nonzero_esto_pair",
                    "fuel_match_method": "unmapped_nonzero_esto_pair",
                }
            )
    if extra_rows:
        candidates_df = pd.concat([candidates_df, pd.DataFrame(extra_rows)], ignore_index=True)

    # Add notes about base-year ESTO nonzero coverage.
    if not candidates_df.empty:
        candidates_df["esto_base_year_nonzero"] = candidates_df.apply(
            lambda row: (row.get("esto_flow", ""), row.get("esto_product", "")) in nonzero_pairs
            if row.get("esto_flow", "") and row.get("esto_product", "") else False,
            axis=1,
        )
        candidates_df["ninth_pair_exists"] = candidates_df.apply(
            lambda row: (row.get("9th_sector", ""), row.get("9th_fuel", "")) in ninth_pairs_set
            if row.get("9th_sector", "") and row.get("9th_fuel", "") else False,
            axis=1,
        )
        candidates_df["mapping_note"] = candidates_df.apply(
            lambda row: "" if row["esto_base_year_nonzero"] else "ESTO base-year zero/absent",
            axis=1,
        )

    # Append remaining unmatched 9th pairs with a note so they still appear in output.
    if not unmatched_df.empty:
        unmapped_rows = unmatched_df.copy()
        unmapped_rows["esto_flow"] = ""
        unmapped_rows["esto_product"] = ""
        unmapped_rows["esto_base_year_nonzero"] = False
        unmapped_rows["ninth_pair_exists"] = True
        unmapped_rows["mapping_note"] = "No ESTO mapping (ESTO base-year zero/absent)"
        candidates_df = pd.concat([candidates_df, unmapped_rows], ignore_index=True)

    # Build strict mapping output that excludes 9th pairs with zero across projected years.
    strict_df = candidates_df.copy()
    if NINTH_FLATTENED_PATH.exists():
        ninth_flat = pd.read_csv(NINTH_FLATTENED_PATH, dtype=str).fillna("")
        year_cols = [
            col
            for col in ninth_flat.columns
            if str(col).isdigit() and int(col) >= PROJECTED_START_YEAR
        ]
        if year_cols:
            numeric = (
                ninth_flat[year_cols]
                .apply(pd.to_numeric, errors="coerce")
                .fillna(0)
            )
            projected_nonzero_mask = numeric.abs().sum(axis=1) != 0
            ninth_projected_pairs = set(
                zip(
                    ninth_flat.loc[projected_nonzero_mask, "sector"],
                    ninth_flat.loc[projected_nonzero_mask, "fuel"],
                )
            )
            # Build hierarchy maps from actual 9th data (unique rows) to support backoff.
            ninth_source = pd.read_csv(
                NINTH_FLATTENED_PATH,
                usecols=["sectors", "sub1sectors", "sub2sectors", "sub3sectors", "sub4sectors", "fuels", "subfuels"],
                dtype=str,
            ).fillna("")
            ninth_source = ninth_source.drop_duplicates()
            sector_columns = ["sectors", "sub1sectors", "sub2sectors", "sub3sectors", "sub4sectors"]
            fuel_columns = ["fuels", "subfuels"]
            sector_parent_map = _build_parent_map_from_data(ninth_source, sector_columns)
            fuel_parent_map = _build_parent_map_from_data(ninth_source, fuel_columns)

            strict_df["orig_9th_sector"] = strict_df["9th_sector"]
            strict_df["orig_9th_fuel"] = strict_df["9th_fuel"]

            # Try hierarchy backoff for rows without an existing 9th pair.
            backoff_mask = (
                (strict_df["ninth_pair_exists"] == False)
                & (strict_df["9th_sector"].fillna("") != "")
                & (strict_df["9th_fuel"].fillna("") != "")
            )
            if backoff_mask.any():
                for idx, row in strict_df.loc[backoff_mask].iterrows():
                    sector_label = row["9th_sector"]
                    fuel_label = row["9th_fuel"]
                    sector_levels = _build_level_chain(sector_label, sector_parent_map)
                    fuel_levels = _build_level_chain(fuel_label, fuel_parent_map)
                    found = False
                    if sector_levels and fuel_levels:
                        # Reduce sector detail first, then fuel detail.
                        for fuel_idx, fuel_level in enumerate(fuel_levels):
                            for sector_level in sector_levels:
                                for sector_candidate in sector_level:
                                    for fuel_candidate in fuel_level:
                                        if (sector_candidate, fuel_candidate) in ninth_projected_pairs:
                                            strict_df.at[idx, "9th_sector"] = sector_candidate
                                            strict_df.at[idx, "9th_fuel"] = fuel_candidate
                                            strict_df.at[idx, "ninth_pair_exists"] = True
                                            strict_df.at[idx, "mapping_note"] = (
                                                f"Hierarchy backoff from {sector_label} / {fuel_label}"
                                            )
                                            found = True
                                            break
                                    if found:
                                        break
                                if found:
                                    break
                            if found:
                                break
            strict_df = strict_df[
                # Keep ESTO base-year nonzero pairs regardless of 9th coverage.
                (strict_df["esto_base_year_nonzero"] == True)
                | (strict_df["9th_sector"].fillna("") == "")
                | (strict_df["9th_fuel"].fillna("") == "")
                | (
                    strict_df.apply(
                        lambda row: (row.get("9th_sector", ""), row.get("9th_fuel", ""))
                        in ninth_projected_pairs,
                        axis=1,
                    )
                )
            ].copy()
            strict_df["mapping_note"] = strict_df["mapping_note"].fillna("")
            strict_df.loc[
                (strict_df["9th_sector"].fillna("") != "")
                & (strict_df["9th_fuel"].fillna("") != ""),
                "mapping_note",
            ] = strict_df["mapping_note"].replace(
                "", f"Filtered to 9th projected nonzero (>= {PROJECTED_START_YEAR})"
            )
            # Only for strict output: clear 9th labels if they don't exist in 9th pairs.
            if "ninth_pair_exists" in strict_df.columns:
                missing_9th_mask = strict_df["ninth_pair_exists"] == False
                if missing_9th_mask.any():
                    strict_df.loc[missing_9th_mask, "9th_sector"] = ""
                    strict_df.loc[missing_9th_mask, "9th_fuel"] = ""
            # Where 9th labels are blank, blank out ninth_pair_exists.
            if "ninth_pair_exists" in strict_df.columns:
                strict_df["ninth_pair_exists"] = strict_df["ninth_pair_exists"].astype(object)
                blank_9th_mask = (
                    (strict_df["9th_sector"].fillna("") == "")
                    | (strict_df["9th_fuel"].fillna("") == "")
                )
                strict_df.loc[blank_9th_mask, "ninth_pair_exists"] = ""

    def _safe_to_csv(df: pd.DataFrame, path: Path, fallback_suffix: str) -> Path:
        try:
            if path.exists():
                os.chmod(path, 0o666)
            df.to_csv(path, index=False)
            return path
        except PermissionError:
            try:
                fallback = path.with_name(path.stem + fallback_suffix + path.suffix)
                df.to_csv(fallback, index=False)
                print(f"[WARN] Failed to write {path} (locked?). Wrote {fallback} instead.")
                return fallback
            except PermissionError:
                tmp_dir = Path("/tmp")
                tmp_dir.mkdir(parents=True, exist_ok=True)
                fallback = tmp_dir / (path.stem + fallback_suffix + path.suffix)
                df.to_csv(fallback, index=False)
                print(f"[WARN] Failed to write {path} (locked?). Wrote {fallback} instead.")
                return fallback

    candidates_path = _safe_to_csv(candidates_df, OUTPUT_PATH, "_new")
    strict_path = _safe_to_csv(strict_df, OUTPUT_STRICT_PATH, "_new")
    unmatched_path = _safe_to_csv(unmatched_df, UNMATCHED_PATH, "_new")
    pd.DataFrame(
        {
            "flows": flow_labels + [""] * max(0, len(product_labels) - len(flow_labels)),
            "products": product_labels + [""] * max(0, len(flow_labels) - len(product_labels)),
        }
    ).to_csv(ESTO_LABELS_PATH, index=False)
    print(f"Wrote mapping candidates to {candidates_path}")
    print(f"Wrote strict projected-nonzero mapping to {strict_path}")
    print(f"Wrote unmatched pairs to {unmatched_path}")
    print(f"Wrote ESTO label list to {ESTO_LABELS_PATH}")


if __name__ == "__main__":
    main()
#%%
